logging:
  receivers:
    webapp:
      type: files
      include_paths:
      - /var/log/webapp.log
  processors:
    parse_json:
      type: parse_json
      time_key: jsonPayload.message.timestamp
      time_format: RFC3339
      target: ""
    move_severity:  
      type: extract_structured
      field: jsonPayload.message
      mappings:
        severity: level
  service:
    pipelines:
      webapp:
        receivers: [webapp]
        processors: [parse_json,move_severity]