logging:
  receivers:
    webapp:
      type: files
      include_paths:
      - /var/log/webapp.log
  processors:
    parse_json:
      type: parse_json
      time_key: jsonPayload.message.timestamp
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.message.level
  service:
    pipelines:
      webapp:
        receivers: [webapp]
        processors: [parse_json,move_severity]