name: integration test

on:
  pull_request:
    branches:
      - main
env:
  PRODUCT_VERSION: "latest"
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
      
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
          version: ${{ env.PRODUCT_VERSION }}

    
    - name: Set up MySQL server
      run: |
        sudo systemctl start mysql
        sudo systemctl status mysql
    
    - name: Create secrets directory
      run: mkdir -p secrets
    
    - name: Set up environment variables
      run: |
        echo "USERNAME=${{ secrets.USERNAME}}" > secrets/secrets.env
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> secrets/secrets.env
        echo "DATABASE=${{ secrets.DATABASE }}" >> secrets/secrets.env
        echo "HOST=${{ secrets.HOST }}" >> secrets/secrets.env

    - name: Create MySQL  database
      run: |
         sudo mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE $DB_NAME;"
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20 

    - name: Install dependencies
      run: npm install
    
    - name: Start the application
      run: |
        npm start &
    
    - name: Wait for the application to be ready
      run: |
        sleep 10
        until curl -s http://localhost:3000; do
          sleep 5
        done

    - name: run test
      run: npm test


    - name: Initialize Packer
      run: packer init packer/image.pkr.hcl
    
    - name: Check Formatting
      run: |
        if !packer fmt -check packer/image.pkr.hcl; then
          echo "Invalid packer format"
          exit 1
        fi

    - name: Validate Packer Template
      run: packer validate packer/image.pkr.hcl

