name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up MySQL server
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server
        sudo service mysql start
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
        sudo mysql -e "FLUSH PRIVILEGES;"
    
    - name: Create secrets directory
      run: mkdir -p secrets
    
    - name: Set up environment variables
      run: |
        echo "DB_USER=${{ secrets.USERNAME }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
        echo "DB_NAME=${{ secrets.DATABASE }}" >> $GITHUB_ENV
        echo "DB_HOST=${{ secrets.HOST }}" >> $GITHUB_ENV
        echo "USERNAME=${{ secrets.USERNAME}}" > secrets/secrets.env
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> secrets/secrets.env
        echo "DATABASE=${{ secrets.DATABASE }}" >> secrets/secrets.env
        echo "HOST=${{ secrets.HOST }}" >> secrets/secrets.env

    - name: Create MySQL user and database
      run: |
        mysql -u root -p $MYSQL_ROOT_PASSWORD -e "CREATE USER '$DB_USER'@'$DB_HOST' IDENTIFIED BY '$DB_PASSWORD';"
        mysql -u root -p $MYSQL_ROOT_PASSWORD -e "CREATE DATABASE $DB_NAME;"
        mysql -u root -p $MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'$DB_HOST';"
        mysql -u root -p $MYSQL_ROOT_PASSWORD -e "FLUSH PRIVILEGES;"
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20 

    - name: Install dependencies
      run: npm install
    
    - name: run test
      run: npm test
