name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: Mad987@#

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up MySQL server
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server
        sudo service mysql start
    
    - name: Create secrets directory
      run: mkdir -p secrets
    
    - name: Set up environment variables
      run: |
        echo "DB_USER=${{ secrets.USERNAME }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
        echo "DB_NAME=${{ secrets.DATABASE }}" >> $GITHUB_ENV
        echo "DB_HOST=${{ secrets.HOST }}" >> $GITHUB_ENV
        echo "USERNAME=${{ secrets.USERNAME}}" > secrets/secrets.env
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> secrets/secrets.env
        echo "DATABASE=${{ secrets.DATABASE }}" >> secrets/secrets.env
        echo "HOST=${{ secrets.HOST }}" >> secrets/secrets.env
    
    - name: Echo env variables
      run: |
        echo "MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD"
        echo "DB_USER: $DB_USER"
        echo "DB_PASSWORD: $DB_PASSWORD"
        echo "DB_NAME: $DB_NAME"
        echo "DB_HOST: $DB_HOST"

    - name: Create MySQL users and database
      run: |
        mysql -u root -pMad987@# -e "CREATE USER '$DB_USER'@'$DB_HOST' IDENTIFIED BY '$DB_PASSWORD';"
        mysql -u root -pMad987@# -e "CREATE DATABASE $DB_NAME;"
        mysql -u root -pMad987@# -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'$DB_HOST';"
        mysql -u root -pMad987@# -e "FLUSH PRIVILEGES;"
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20 

    - name: Install dependencies
      run: npm install
    
    - name: run test
      run: npm test
